### ISSUE TITLE
creds leak?

### ISSUE THREAD

**Issue by aytvill** [zivawernick/2022mondayApp#1]
USDA-Food-Data-Central-notes seem to leak creds, they are probably obsolete, yet it's good for CV/portfolio to keep creds off

**Comment by zivawernick** [comment]
Can you help me with this? I don't use github for work, and haven't ever
been very good with it. I try using it for hackathons and projects even
ones i haven't completed but now I can't seem to get into the file
correctly to edit it and the merge a new version with just the first two
lines (the link without the credentials information)

thanks
Ziva Wernick
Connect with me on LinkedIn <https://www.linkedin.com/in/ziva-wernick/>

**Comment by aytvill** [comment]
@zivawernick open PR section and confirm my pull request, it will remove everything from surface.

I removed everything personal **from surface** if you want more, that could be done too. Feel free to contact me for any other help/support.
